logs:
  - name: root
    level: 0
    appender:
      - type: 1
        formatter: "[%d] [%p] [%f:%l]%T [%t] %m%n"
        file: "/home/xubin/Desktop/WebServer/log/test_root_log.txt"
  - name: file
    level: 4
    appender:
      - type: 1
        formatter: "[%d] [%p] [%f:%l]%T [%t] %m%n"
        file: "/home/xubin/Websever/log/logtest_file_log.txt"
  - name: stdout
    level: 0
    appender:
      - type: 0
        formatter: "[%d] [%p] [%f:%l] [%t] %T%m%n"
        # file: "/home/xubin/Desktop/WebServer/log/test_root_log.txt"


system:
  port: 8088