logs:
  - name: root
    level: 0
    appender:
      - type: 1
        formatter: "[%d] [%t] [%p] [%f:%l]%T%m%n"
        file: "/home/xubin/Websever/log/test_root_log.txt"
  - name: file
    level: 4
    appender:
      - type: 1
        formatter: "[%d] [%t] [%p] [%f:%l]%T%m%n"
        file: "/home/xubin/Websever/log/logtest_file_log.txt"

system:
  port: 8088